# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20170315_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliders',
            name='image',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
