# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20170315_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='video',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0432\u0438\u0434\u0435\u043e \u0441 Youtube'),
        ),
    ]
