# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_en',
            field=models.CharField(max_length=300, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0441'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_kk',
            field=models.CharField(max_length=300, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0441'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0441'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title',
            field=models.CharField(default='\u0420\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u044b', max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
