# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='title',
            field=models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
