# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20170325_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
