# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20170330_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourism',
            name='image',
            field=models.ImageField(default=1, upload_to='images/tourism', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 \u0443\u0441\u0442\u043e\u0439\u0447\u0438\u0432\u044b\u0439 \u0442\u0443\u0440\u0438\u0437\u043c'),
            preserve_default=False,
        ),
    ]
