# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_tourism_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='link',
        ),
        migrations.AddField(
            model_name='publications',
            name='image',
            field=models.ImageField(default='1', upload_to='images/publication', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'),
        ),
    ]
