# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20170330_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='\u0420\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u043b\u043e\u0433\u043e\u0442\u0438\u043f\u044b', max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('image', models.ImageField(upload_to='images/logo', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u043e\u0433\u043e')),
            ],
            options={
                'verbose_name': '\u041b\u043e\u0433\u043e\u0442\u0438\u043f',
                'verbose_name_plural': '\u041b\u043e\u0433\u043e\u0442\u0438\u043f\u044b',
            },
        ),
    ]
