# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='image_en',
            field=models.ImageField(null=True, upload_to='images/logo', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u043e\u0433\u043e'),
        ),
        migrations.AddField(
            model_name='logo',
            name='image_kk',
            field=models.ImageField(null=True, upload_to='images/logo', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u043e\u0433\u043e'),
        ),
        migrations.AddField(
            model_name='logo',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='images/logo', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u043e\u0433\u043e'),
        ),
    ]
