# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_auto_20170413_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u0430 - 1920x500px'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(upload_to='images/logo', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u043e\u0433\u043e - 241x109px'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image_en',
            field=models.ImageField(null=True, upload_to='images/logo', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u043e\u0433\u043e - 241x109px'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image_kk',
            field=models.ImageField(null=True, upload_to='images/logo', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u043e\u0433\u043e - 241x109px'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='images/logo', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u043e\u0433\u043e - 241x109px'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='image',
            field=models.ImageField(default='1', upload_to='images/publication', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438 - 200x200px'),
        ),
        migrations.AlterField(
            model_name='slidermask',
            name='image',
            field=models.ImageField(upload_to='images/slider_masks', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043c\u0430\u0441\u043a\u0438 - 550x485px'),
        ),
        migrations.AlterField(
            model_name='slidermask',
            name='image_en',
            field=models.ImageField(null=True, upload_to='images/slider_masks', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043c\u0430\u0441\u043a\u0438 - 550x485px'),
        ),
        migrations.AlterField(
            model_name='slidermask',
            name='image_kk',
            field=models.ImageField(null=True, upload_to='images/slider_masks', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043c\u0430\u0441\u043a\u0438 - 550x485px'),
        ),
        migrations.AlterField(
            model_name='slidermask',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='images/slider_masks', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043c\u0430\u0441\u043a\u0438 - 550x485px'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='image',
            field=models.ImageField(upload_to='images/sliders', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430 - 1920x660px'),
        ),
        migrations.AlterField(
            model_name='tourism',
            name='image',
            field=models.ImageField(upload_to='images/tourism', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 \u0443\u0441\u0442\u043e\u0439\u0447\u0438\u0432\u044b\u0439 \u0442\u0443\u0440\u0438\u0437\u043c - 790x780px'),
        ),
    ]
