# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 09:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20170422_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpirienceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/local', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 \u043e\u0431\u043c\u0435\u043d\u0430 \u043e\u043f\u044b\u0442\u043e\u043c - 790x780px')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043e\u0431\u043c\u0435\u043d\u0430 \u043e\u043f\u044b\u0442\u043e\u043c')),
            ],
            options={
                'verbose_name': '\u041e\u0431\u043c\u0435\u043d \u043e\u043f\u044b\u0442\u043e\u043c',
                'verbose_name_plural': '\u041e\u0431\u043c\u0435\u043d \u043e\u043f\u044b\u0442\u043e\u043c',
            },
        ),
        migrations.CreateModel(
            name='LocalLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/local', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 \u043c\u0435\u0441\u0442\u043d\u044b\u0435 \u0438\u043d\u0438\u0446\u0438\u0430\u0442\u0438\u0432\u044b - 790x780px')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043c\u0435\u0441\u0442\u043d\u044b\u0445 \u0438\u043d\u0438\u0446\u0438\u0430\u0442\u0438\u0432')),
            ],
            options={
                'verbose_name': '\u041c\u0435\u0441\u0442\u043d\u0430\u044f \u0438\u043d\u0438\u0446\u0438\u0430\u0442\u0438\u0432\u0430',
                'verbose_name_plural': '\u041c\u0435\u0441\u0442\u043d\u044b\u0435 \u0438\u043d\u0438\u0446\u0438\u0430\u0442\u0438\u0432\u044b',
            },
        ),
        migrations.AlterModelOptions(
            name='socialprojects',
            options={'verbose_name': '\u0421\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u0435\u0434\u043f\u0440\u0438\u043d\u0438\u043c\u0430\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u043e', 'verbose_name_plural': '\u0421\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u0435\u0434\u043f\u0440\u0438\u043d\u0438\u043c\u0430\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u043e'},
        ),
    ]
