# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_auto_20170502_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiriencechange',
            name='image',
        ),
        migrations.RemoveField(
            model_name='locallead',
            name='image',
        ),
    ]
