# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 08:46
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_auto_20170502_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='pre_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0410\u043d\u043e\u043d\u0441 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u0430'),
        ),
        migrations.AddField(
            model_name='articles',
            name='pre_text_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0410\u043d\u043e\u043d\u0441 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u0430'),
        ),
        migrations.AddField(
            model_name='articles',
            name='pre_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0410\u043d\u043e\u043d\u0441 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u0430'),
        ),
    ]
