# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    def forwards(self, orm):
        order = 0
        for obj in orm.MyModel.objects.all():
            order += 1
            obj.my_order = order
            obj.save()

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'ordering': ('my_order',), 'verbose_name': '\u041f\u0430\u0440\u0442\u043d\u0435\u0440', 'verbose_name_plural': '\u041f\u0430\u0440\u0442\u043d\u0435\u0440\u044b'},
        ),
        migrations.AddField(
            model_name='partners',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
