# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainconcepts',
            old_name='slow_food_imgage',
            new_name='slow_food_image',
        ),
    ]
