# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_auto_20170320_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainconcepts',
            name='climate_image',
            field=models.ImageField(default=1, upload_to='images/main', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0435 \u043a\u043b\u0438\u043c\u0430\u0442\u0430'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainconcepts',
            name='development_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/main', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0443\u0441\u0442\u043e\u0439\u0447\u0438\u0432\u043e\u0433\u043e \u0440\u0430\u0437\u0432\u0438\u0442\u0438\u044f'),
            preserve_default=False,
        ),
    ]
