# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0003_auto_20170330_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainconcepts',
            name='climate_image',
            field=models.ImageField(upload_to='images/main', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0435 \u043a\u043b\u0438\u043c\u0430\u0442\u0430 - 790x780px'),
        ),
        migrations.AlterField(
            model_name='mainconcepts',
            name='development_image',
            field=models.ImageField(upload_to='images/main', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0443\u0441\u0442\u043e\u0439\u0447\u0438\u0432\u043e\u0433\u043e \u0440\u0430\u0437\u0432\u0438\u0442\u0438\u044f - 790x780px'),
        ),
        migrations.AlterField(
            model_name='mainconcepts',
            name='slow_food_image',
            field=models.ImageField(upload_to='images/concepts', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f Slow food - 790x780px'),
        ),
    ]
