# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0005_auto_20170502_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainconcepts',
            name='bio_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/main', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0431\u0438\u043e\u043a\u0443\u043b\u044c\u0442\u0443\u0440\u043d\u043e\u0435 \u0440\u0430\u0437\u043d\u043e\u043e\u0431\u0440\u0430\u0437\u0438\u0435 - 790x780p'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainconcepts',
            name='bio',
            field=models.TextField(verbose_name='\u0411\u0438\u043e\u043a\u0443\u043b\u044c\u0442\u0443\u0440\u043d\u043e\u0435 \u0440\u0430\u0437\u043d\u043e\u043e\u0431\u0440\u0430\u0437\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='mainconcepts',
            name='bio_en',
            field=models.TextField(null=True, verbose_name='\u0411\u0438\u043e\u043a\u0443\u043b\u044c\u0442\u0443\u0440\u043d\u043e\u0435 \u0440\u0430\u0437\u043d\u043e\u043e\u0431\u0440\u0430\u0437\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='mainconcepts',
            name='bio_kk',
            field=models.TextField(null=True, verbose_name='\u0411\u0438\u043e\u043a\u0443\u043b\u044c\u0442\u0443\u0440\u043d\u043e\u0435 \u0440\u0430\u0437\u043d\u043e\u043e\u0431\u0440\u0430\u0437\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='mainconcepts',
            name='bio_ru',
            field=models.TextField(null=True, verbose_name='\u0411\u0438\u043e\u043a\u0443\u043b\u044c\u0442\u0443\u0440\u043d\u043e\u0435 \u0440\u0430\u0437\u043d\u043e\u043e\u0431\u0440\u0430\u0437\u0438\u0435'),
        ),
    ]
