# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e \u0432\u0432\u0435\u0434\u0438\u0442\u0435 \u043e \u043d\u0430\u0441')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='\u041f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e \u0432\u0432\u0435\u0434\u0438\u0442\u0435 \u043e \u043d\u0430\u0441')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='\u041f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e \u0432\u0432\u0435\u0434\u0438\u0442\u0435 \u043e \u043d\u0430\u0441')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='\u041f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e \u0432\u0432\u0435\u0434\u0438\u0442\u0435 \u043e \u043d\u0430\u0441')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043e \u043d\u0430\u0441')),
                ('text_ru', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043e \u043d\u0430\u0441')),
                ('text_en', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043e \u043d\u0430\u0441')),
                ('text_kk', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043e \u043d\u0430\u0441')),
                ('our_see', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043d\u0430\u0448\u0435 \u0432\u0438\u0434\u0435\u043d\u044c\u0435')),
                ('our_see_ru', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043d\u0430\u0448\u0435 \u0432\u0438\u0434\u0435\u043d\u044c\u0435')),
                ('our_see_en', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043d\u0430\u0448\u0435 \u0432\u0438\u0434\u0435\u043d\u044c\u0435')),
                ('our_see_kk', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043d\u0430\u0448\u0435 \u0432\u0438\u0434\u0435\u043d\u044c\u0435')),
                ('mission', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043d\u0430\u0448\u0430 \u043c\u0438\u0441\u0441\u0438\u044f')),
                ('mission_ru', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043d\u0430\u0448\u0430 \u043c\u0438\u0441\u0441\u0438\u044f')),
                ('mission_en', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043d\u0430\u0448\u0430 \u043c\u0438\u0441\u0441\u0438\u044f')),
                ('mission_kk', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043d\u0430\u0448\u0430 \u043c\u0438\u0441\u0441\u0438\u044f')),
                ('target1_image', models.ImageField(upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u0435\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target1_image_ru', models.ImageField(null=True, upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u0435\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target1_image_en', models.ImageField(null=True, upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u0435\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target1_image_kk', models.ImageField(null=True, upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u0435\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target1_text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441 \u0434\u043b\u044f \u043b\u0435\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target1_text_ru', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441 \u0434\u043b\u044f \u043b\u0435\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target1_text_en', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441 \u0434\u043b\u044f \u043b\u0435\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target1_text_kk', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441 \u0434\u043b\u044f \u043b\u0435\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target2_image', models.ImageField(upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043f\u0440\u0430\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target2_image_ru', models.ImageField(null=True, upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043f\u0440\u0430\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target2_image_en', models.ImageField(null=True, upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043f\u0440\u0430\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target2_image_kk', models.ImageField(null=True, upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043f\u0440\u0430\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target2_text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441 \u0434\u043b\u044f \u043f\u0440\u0430\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target2_text_ru', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441 \u0434\u043b\u044f \u043f\u0440\u0430\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target2_text_en', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441 \u0434\u043b\u044f \u043f\u0440\u0430\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('target2_text_kk', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441 \u0434\u043b\u044f \u043f\u0440\u0430\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430')),
                ('partner1', models.ImageField(upload_to='images/about_us', verbose_name='\u041b\u043e\u0433\u043e \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430')),
                ('partner2', models.ImageField(upload_to='images/about_us', verbose_name='\u041b\u043e\u0433\u043e \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u041e \u043d\u0430\u0441',
                'verbose_name_plural': '\u041e \u043d\u0430\u0441',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430')),
                ('text', models.CharField(max_length=500, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.AboutUs', verbose_name='\u041e \u043d\u0430\u0441')),
            ],
            options={
                'verbose_name': '\u041f\u0430\u0440\u0442\u043d\u0435\u0440',
                'verbose_name_plural': '\u041f\u0430\u0440\u0442\u043d\u0435\u0440',
            },
        ),
    ]
