# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='target1_image_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='target1_image_kk',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='target1_image_ru',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='target2_image_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='target2_image_kk',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='target2_image_ru',
        ),
    ]
