# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20170316_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='text_en',
            field=models.CharField(max_length=500, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='partners',
            name='text_kk',
            field=models.CharField(max_length=500, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='partners',
            name='text_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='partners',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='partners',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='partners',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430'),
        ),
    ]
