# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20170316_1925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partnerss',
        ),
    ]
