# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20170324_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default=1, upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 \u043e \u043d\u0430\u0441'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='mission_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0434\u043b\u044f \u043d\u0430\u0448\u0435\u0439 \u043c\u0438\u0441\u0441\u0438\u0438'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='our_see_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043d\u0430\u0448\u0435\u0433\u043e \u0432\u0438\u0434\u0435\u043d\u044c\u044f'),
            preserve_default=False,
        ),
    ]
