# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20170330_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='partner_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u044b'),
        ),
    ]
