# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_aboutus_partner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='mission_image',
            field=models.ImageField(upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0434\u043b\u044f \u043d\u0430\u0448\u0435\u0439 \u043c\u0438\u0441\u0441\u0438\u0438 - 790x780px'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_see_image',
            field=models.ImageField(upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043d\u0430\u0448\u0435\u0433\u043e \u0432\u0438\u0434\u0435\u043d\u044c\u044f - 790x780px'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='partner1',
            field=models.ImageField(upload_to='images/about_us', verbose_name='\u041b\u043e\u0433\u043e \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430 - 349x115px'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='partner2',
            field=models.ImageField(upload_to='images/about_us', verbose_name='\u041b\u043e\u0433\u043e \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430 - 349x115px'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='partner_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u044b - 790x780px'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='target1_image',
            field=models.ImageField(upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u0435\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 - 790x780px'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='target2_image',
            field=models.ImageField(upload_to='images/about_us', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043f\u0440\u0430\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 - 790x780px'),
        ),
    ]
