# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_link', models.CharField(max_length=300, verbose_name='facebook')),
                ('t_link', models.CharField(max_length=300, verbose_name='twitter')),
                ('i_link', models.CharField(max_length=300, verbose_name='instagramm')),
                ('y_link', models.CharField(max_length=300, verbose_name='youtube')),
            ],
            options={
                'verbose_name': '\u0421\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0435\u0442\u044c',
                'verbose_name_plural': '\u0421\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 \u0441\u0435\u0442\u0438',
            },
        ),
    ]
